## template sensors ##

- platform: template
  sensors:
    # amount to charge car by on for Octopus Intelligent Go
    oig_charge_needed:
      friendly_name: "OIG charge needed"
      unit_of_measurement: "%"
      icon_template: "mdi:ev-station"
      value_template: >-
        {% set needed = states('sensor.piglet_target_state_of_charge') | int - states('sensor.piglet_state_of_charge') | int %}
        {% set needed = needed + 10 if needed > 10 else 10 %}
        {% set needed = needed if needed < 100 else 100 %}
        {{ needed }}
